# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: de13bd59b9ff115fc4582e783101cb622ddf56504bd5e7344e943a7a7984adb0cbde024c00fcc3509d9b98e5fb43d72e138d7d3b698a3dd10eae9b1490056743

test:
  secret_key_base: 44e624ac907480d99f0a70877461e959d8ca2bb7a23448d0990f0ffabb78bb65ab5705fb2a7224ecf05230f792d76fee58bd8aea910d1604af6d272607bb3f65

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
